// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-rfVP_tnn7F8F2sFbxk3-PvuFsgL9P2U',
    appId: '1:984269426617:web:b2b4380ccc4a6405ad3068',
    messagingSenderId: '984269426617',
    projectId: 'instagarm-clone-1001e',
    authDomain: 'instagarm-clone-1001e.firebaseapp.com',
    storageBucket: 'instagarm-clone-1001e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg0K_AmzZFRz10fZFiIDEcySPfinVJqJ4',
    appId: '1:984269426617:android:d09f604acb1c14d1ad3068',
    messagingSenderId: '984269426617',
    projectId: 'instagarm-clone-1001e',
    storageBucket: 'instagarm-clone-1001e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKXyQ30e2fGE-sztSFdogS8WoD1iZ2Stg',
    appId: '1:984269426617:ios:71f30364d3a3f1daad3068',
    messagingSenderId: '984269426617',
    projectId: 'instagarm-clone-1001e',
    storageBucket: 'instagarm-clone-1001e.appspot.com',
    iosClientId: '984269426617-ogfp8gsfcvlg7fghq4kkkvpmlk20ve0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaApp',
  );
}
